name: Build custom coredns binary
on:
  push:

env:
  COREDNS_VERSION: 1.8.7
  GO_VERSION: 1.17.7

jobs:
  build-coredns:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone coredns
        uses: actions/checkout@v2
        with:
          repository: coredns/coredns
          path: coredns-src
          ref: v${{ env.COREDNS_VERSION }}

      - name: Setup go version
        uses: actions/setup-go@v2
        with:
          go-version: "^${{ env.GO_VERSION }}"

      - run: 'echo "autoipv6ptr:github.com/cornelicorn/coredns-auto-aaaa-and-ptr/autoipv6ptr" >> coredns-src/plugin.cfg'
      - run: go generate coredns.go
        working-directory: coredns-src
      - run: go get
        working-directory: coredns-src
      - run: make -C coredns-src -f Makefile.release release

      - run: coredns-src/build/linux/amd64/coredns -version
      - run: coredns-src/build/linux/amd64/coredns -plugins
      - run: ls coredns-src/release

      - name: upload releases to cache
        uses: actions/cache@v2
        id: coredns-release
        with:
          path: coredns-src/release/*
          key: ${{ github.sha }}

  upload-binaries:
    needs: [ build-coredns ]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        variant:
          - darwin_amd64
          - linux_amd64
          - linux_arm64
          - linux_arm
          - linux_mips64le
          - linux_mips
          - linux_ppc64le
          - linux_s390x
          - windows_amd64
    steps:
      - name: restore releases from cache
        uses: actions/cache@v2
        id: coredns-release
        with:
          path: coredns-src/release/*
          key: ${{ github.sha }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.variant }}
          path: coredns-src/release/coredns_${{ env.COREDNS_VERSION }}_${{ matrix.variant }}.tgz

