name: Build custom coredns binary
on:
  push:

env:
  COREDNS_VERSION: v1.8.7

jobs:
  build-coredns:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone coredns
        uses: actions/checkout@v2
        with:
          repository: coredns/coredns
          path: coredns-src
          ref: ${{ env.COREDNS_VERSION }}

      - name: Setup go version
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.6'

      - run: 'echo "autoipv6ptr:github.com/cornelicorn/coredns-auto-aaaa-and-ptr/autoipv6ptr" >> coredns-src/plugin.cfg'
      - run: cd coredns-src
      - run: go generate coredns.go
      - run: ls
      - run: make -f Makefile.release release

      - run: build/linux/amd64/coredns -version
      - run: build/linux/amd64/coredns -plugins

      - run: ls release

  upload-binaries:
    needs: [ build-coredns ]
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        variant:
          - darwin_amd64
          - linux_amd64
          - linux_arm64
          - linux_arm
          - linux_mips64le
          - linux_mips
          - linux_ppc64le
          - linux_s390x
          - windows_amd64
    steps:
      - run: pwd

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.variant }}
          path: coredns-src/release/coredns_${{ env.COREDNS_VERSION }}_${{ matrix.variant }}.tgz

